# ci-cd.yaml
name: CI-CD Pipeline

on:
  push:
    branches:
      - devops1

env:
  AWS_REGION: us-east-1

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        service:
          - auth-service
          - user-service
          - order-service

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ matrix.service }}:latest \
            ./services/${{ matrix.service }}

      - name: Tag Docker Image
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          docker tag \
            ${{ matrix.service }}:latest \
            ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${{ matrix.service }}:latest

      - name: Push Docker Image to  ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          docker push \
            ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${{ matrix.service }}:latest
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    needs:
      - build-and-push

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name prod-eks-cluster

      - name: Deploy Kubernetes Resources
        run: |
          kubectl apply -f kubernetes/auth-service/
          kubectl apply -f kubernetes/user-service/
          kubectl apply -f kubernetes/order-service/